--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/gameapi
branches:
- master
projects:
  gameapi:
    path: ""
    model: virion
    type: library
    libs:
    - src: thebigsmilexd/apibossbar/apibossbar
      version: ^0.0.3
...
